# Generated by Django 3.0.6 on 2020-05-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRCSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
